### ISSUE TITLE
window.plausible is not a function

### ISSUE THREAD

**Issue by durbanitas** [botanicastudios/plausible-vue#3]
thanks for this.

It works, but I get the following error in the console on production: `Uncaught TypeError: window.plausible is not a function`

we use vue and vue-router and have everything prerendered

any idea what causes this?

**Comment by tobymarsden** [comment]
Hi @durbanitas -- did you figure this out?

**Comment by durbanitas** [comment]
> Hi @durbanitas -- did you figure this out?

Hi, no - had to build an own solution.
